USE ROLE ACCOUNTADMIN;
CREATE DATABASE KUSTOM_TEST;
CREATE DATABASE KUSTOM_PROD;

USE DATABASE KUSTOM_TEST;
CREATE OR REPLACE SCHEMA KUSTOM_TEST.SAGE_PREPARED;
CREATE OR REPLACE SCHEMA KUSTOM_TEST.SAGE_INTACCT_PREPARED;
CREATE OR REPLACE SCHEMA KUSTOM_TEST.DASH_PREPARED;
CREATE OR REPLACE SCHEMA KUSTOM_TEST.MASTER_PREPARED;
CREATE OR REPLACE SCHEMA KUSTOM_TEST.FACT_PREPARED;
CREATE OR REPLACE SCHEMA KUSTOM_TEST.MASTER_STG;
CREATE OR REPLACE SCHEMA KUSTOM_TEST.FACT_STG;