CREATE OR REPLACE VIEW KUSTOM_RAW.SAGE_DB_DBO.VW_JCM_MASTER_COST_CODES as (
    SELECT 
        CONCAT(JOB, '-', COST_CODE) AS JC_KEY,
        *
    FROM KUSTOM_RAW.SAGE_DB_DBO.JCM_MASTER__COST_CODE
    WHERE 
        _fivetran_deleted = FALSE 
        AND COST_CODE NOT LIKE '%-000' 
        AND EXTRA <> '99-FCA'
)
;

SELECT * FROM KUSTOM_RAW.SAGE_DB_DBO.VW_JCM_MASTER_COST_CODES
WHERE JC_KEY = '23-04-72994-99-FCA'
;

SELECT 
    JC_KEY,
    JC_KEY_COUNT
FROM (
    SELECT
        JC_KEY,
        COUNT(JC_KEY) AS JC_KEY_COUNT
    FROM KUSTOM_RAW.SAGE_DB_DBO.VW_JCM_MASTER_COST_CODES
    GROUP BY JC_KEY
)
WHERE JC_KEY_COUNT > 1
;